FROM python:3.13-alpine

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    USER=app \
    UID=1000 \
    GID=1000 \
    MPLCONFIGDIR=/tmp

RUN apk add --no-cache \
        build-base \
        libjpeg-turbo-dev \
        zlib-dev \
        libpng-dev \
        freetype-dev \
        fontconfig \
    && addgroup -g ${GID} -S ${USER} \
    && adduser -u ${UID} -S ${USER} -G ${USER}

WORKDIR /app

COPY . /app
RUN chown -R ${UID}:${GID} /app

RUN pip install --upgrade --no-cache-dir pip \
 && if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi

USER ${USER}

EXPOSE 8000
ENTRYPOINT ["uvicorn"]
CMD ["run:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app"]
