FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    USER=veecvolley \
    DEBIAN_FRONTEND=noninteractive \
    MPLCONFIGDIR=/tmp

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        libjpeg-dev \
        zlib1g-dev \
        libpng-dev \
        libfreetype6-dev \
        fontconfig \
        && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN addgroup --system ${USER} && adduser --system --ingroup ${USER} ${USER} \
 && chown -R ${USER}:${USER} /app

RUN pip install --upgrade --no-warn-script-location pip \
 && if [ -f requirements.txt ]; then pip install --no-warn-script-location --no-cache-dir -r requirements.txt; fi

USER ${USER}

EXPOSE 8000
ENTRYPOINT ["uvicorn"]
CMD ["serve:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app"]